appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: QXPzECS4QIUxKZsHN201ncJwUynERkXmYdfQar7bW01ngAWOi9ylAGwh2RAuSQ1FeDBJB1Gn8WWiu5BEwb5Gh1O5OuYIvbEvL81Hzmt8xVtzKq+mTL2N+T6E4rvHaoKr1h6VVM3IBeRoFx+ts2bhY1KMUsYwy4s8Kf17IfPHmbKhNhSGSrZdDghBId4PIaqfIRUS0LtaWGTIyYVjn2Q42fzrQAjFJC5DUQSGGiD6dYeNnihJjY0ifiOxpiRrEuCRNEyfRgwiq4Fn5aTuxL1GyANpGZa8z233kJbQO4A7DQxvxG/ehdlky0uOLzVhJVLznKpadGlw3FYKRES23+HyzdgqkV7Nfn+yNzgHiF5vhWD4osPRd+9rMnVSGCt0pwioDXR81h2gt7w4G2Okjn2tssTHFSJCeLGLSl7zZURVNwVCJs6lQOMSxFDq/0s8uzJQ90pFBkW/GpFf3Cz5X2sg6LaiiWZ2Puktk/xjtOx0thUM9BlqfL28MUYLb+R113OOfv84q9DteDutzwFxpOiEGD4UbkWUdTY4GaIkmqmc7JBrHMw4yxK9DZLeKVnyP0POQJYevRqiTKk7gOcZv7scL9MLT2SY+81p9WKFdGFiH4XcOjD0sANYiThhs2aLb2LQOzty6ngUxReyhgQVVK94UncirrnqCdYZItRQ9KDQOJQ=
conda_forge_output_validation: false
